// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: identity.proto

package identitypb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RegisterOrGetTelegramUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    string                 `protobuf:"bytes,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	ChatId        string                 `protobuf:"bytes,4,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Meta          *structpb.Struct       `protobuf:"bytes,5,opt,name=meta,proto3" json:"meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOrGetTelegramUserRequest) Reset() {
	*x = RegisterOrGetTelegramUserRequest{}
	mi := &file_identity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOrGetTelegramUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOrGetTelegramUserRequest) ProtoMessage() {}

func (x *RegisterOrGetTelegramUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOrGetTelegramUserRequest.ProtoReflect.Descriptor instead.
func (*RegisterOrGetTelegramUserRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{0}
}

func (x *RegisterOrGetTelegramUserRequest) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

func (x *RegisterOrGetTelegramUserRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *RegisterOrGetTelegramUserRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *RegisterOrGetTelegramUserRequest) GetChatId() string {
	if x != nil {
		return x.ChatId
	}
	return ""
}

func (x *RegisterOrGetTelegramUserRequest) GetMeta() *structpb.Struct {
	if x != nil {
		return x.Meta
	}
	return nil
}

type RegisterOrGetTelegramUserResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterOrGetTelegramUserResponse) Reset() {
	*x = RegisterOrGetTelegramUserResponse{}
	mi := &file_identity_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterOrGetTelegramUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterOrGetTelegramUserResponse) ProtoMessage() {}

func (x *RegisterOrGetTelegramUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterOrGetTelegramUserResponse.ProtoReflect.Descriptor instead.
func (*RegisterOrGetTelegramUserResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterOrGetTelegramUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByTelegramIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TelegramId    string                 `protobuf:"bytes,1,opt,name=telegram_id,json=telegramId,proto3" json:"telegram_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTelegramIdRequest) Reset() {
	*x = GetUserByTelegramIdRequest{}
	mi := &file_identity_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTelegramIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTelegramIdRequest) ProtoMessage() {}

func (x *GetUserByTelegramIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTelegramIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByTelegramIdRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserByTelegramIdRequest) GetTelegramId() string {
	if x != nil {
		return x.TelegramId
	}
	return ""
}

type GetUserByTelegramIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByTelegramIdResponse) Reset() {
	*x = GetUserByTelegramIdResponse{}
	mi := &file_identity_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByTelegramIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByTelegramIdResponse) ProtoMessage() {}

func (x *GetUserByTelegramIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByTelegramIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByTelegramIdResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserByTelegramIdResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type GetUserByUserIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUserIdRequest) Reset() {
	*x = GetUserByUserIdRequest{}
	mi := &file_identity_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUserIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUserIdRequest) ProtoMessage() {}

func (x *GetUserByUserIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUserIdRequest.ProtoReflect.Descriptor instead.
func (*GetUserByUserIdRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserByUserIdRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserByUserIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Profile       *Profile               `protobuf:"bytes,1,opt,name=profile,proto3" json:"profile,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserByUserIdResponse) Reset() {
	*x = GetUserByUserIdResponse{}
	mi := &file_identity_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserByUserIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserByUserIdResponse) ProtoMessage() {}

func (x *GetUserByUserIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserByUserIdResponse.ProtoReflect.Descriptor instead.
func (*GetUserByUserIdResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserByUserIdResponse) GetProfile() *Profile {
	if x != nil {
		return x.Profile
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_identity_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{6}
}

func (x *HealthRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_identity_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{7}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Profile struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Profile) Reset() {
	*x = Profile{}
	mi := &file_identity_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Profile) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Profile) ProtoMessage() {}

func (x *Profile) ProtoReflect() protoreflect.Message {
	mi := &file_identity_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Profile.ProtoReflect.Descriptor instead.
func (*Profile) Descriptor() ([]byte, []int) {
	return file_identity_proto_rawDescGZIP(), []int{8}
}

func (x *Profile) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Profile) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Profile) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

var File_identity_proto protoreflect.FileDescriptor

const file_identity_proto_rawDesc = "" +
	"\n" +
	"\x0eidentity.proto\x12\bidentity\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/protobuf/struct.proto\"\xc5\x01\n" +
	" RegisterOrGetTelegramUserRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\tR\n" +
	"telegramId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x17\n" +
	"\achat_id\x18\x04 \x01(\tR\x06chatId\x12+\n" +
	"\x04meta\x18\x05 \x01(\v2\x17.google.protobuf.StructR\x04meta\"<\n" +
	"!RegisterOrGetTelegramUserResponse\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"=\n" +
	"\x1aGetUserByTelegramIdRequest\x12\x1f\n" +
	"\vtelegram_id\x18\x01 \x01(\tR\n" +
	"telegramId\"J\n" +
	"\x1bGetUserByTelegramIdResponse\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.identity.ProfileR\aprofile\"1\n" +
	"\x16GetUserByUserIdRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"F\n" +
	"\x17GetUserByUserIdResponse\x12+\n" +
	"\aprofile\x18\x01 \x01(\v2\x11.identity.ProfileR\aprofile\"=\n" +
	"\rHealthRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"^\n" +
	"\aProfile\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName2\x88\x03\n" +
	"\x0fIdentityService\x12v\n" +
	"\x19RegisterOrGetTelegramUser\x12*.identity.RegisterOrGetTelegramUserRequest\x1a+.identity.RegisterOrGetTelegramUserResponse\"\x00\x12d\n" +
	"\x13GetUserByTelegramId\x12$.identity.GetUserByTelegramIdRequest\x1a%.identity.GetUserByTelegramIdResponse\"\x00\x12X\n" +
	"\x0fGetUserByUserId\x12 .identity.GetUserByUserIdRequest\x1a!.identity.GetUserByUserIdResponse\"\x00\x12=\n" +
	"\x06Health\x12\x17.identity.HealthRequest\x1a\x18.identity.HealthResponse\"\x00BUZSgithub.com/nikitadev-work/SyncBuyProject/services/identity/proto-codegen;identitypbb\x06proto3"

var (
	file_identity_proto_rawDescOnce sync.Once
	file_identity_proto_rawDescData []byte
)

func file_identity_proto_rawDescGZIP() []byte {
	file_identity_proto_rawDescOnce.Do(func() {
		file_identity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)))
	})
	return file_identity_proto_rawDescData
}

var file_identity_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_identity_proto_goTypes = []any{
	(*RegisterOrGetTelegramUserRequest)(nil),  // 0: identity.RegisterOrGetTelegramUserRequest
	(*RegisterOrGetTelegramUserResponse)(nil), // 1: identity.RegisterOrGetTelegramUserResponse
	(*GetUserByTelegramIdRequest)(nil),        // 2: identity.GetUserByTelegramIdRequest
	(*GetUserByTelegramIdResponse)(nil),       // 3: identity.GetUserByTelegramIdResponse
	(*GetUserByUserIdRequest)(nil),            // 4: identity.GetUserByUserIdRequest
	(*GetUserByUserIdResponse)(nil),           // 5: identity.GetUserByUserIdResponse
	(*HealthRequest)(nil),                     // 6: identity.HealthRequest
	(*HealthResponse)(nil),                    // 7: identity.HealthResponse
	(*Profile)(nil),                           // 8: identity.Profile
	(*structpb.Struct)(nil),                   // 9: google.protobuf.Struct
	(*emptypb.Empty)(nil),                     // 10: google.protobuf.Empty
}
var file_identity_proto_depIdxs = []int32{
	9,  // 0: identity.RegisterOrGetTelegramUserRequest.meta:type_name -> google.protobuf.Struct
	8,  // 1: identity.GetUserByTelegramIdResponse.profile:type_name -> identity.Profile
	8,  // 2: identity.GetUserByUserIdResponse.profile:type_name -> identity.Profile
	10, // 3: identity.HealthRequest.empty:type_name -> google.protobuf.Empty
	0,  // 4: identity.IdentityService.RegisterOrGetTelegramUser:input_type -> identity.RegisterOrGetTelegramUserRequest
	2,  // 5: identity.IdentityService.GetUserByTelegramId:input_type -> identity.GetUserByTelegramIdRequest
	4,  // 6: identity.IdentityService.GetUserByUserId:input_type -> identity.GetUserByUserIdRequest
	6,  // 7: identity.IdentityService.Health:input_type -> identity.HealthRequest
	1,  // 8: identity.IdentityService.RegisterOrGetTelegramUser:output_type -> identity.RegisterOrGetTelegramUserResponse
	3,  // 9: identity.IdentityService.GetUserByTelegramId:output_type -> identity.GetUserByTelegramIdResponse
	5,  // 10: identity.IdentityService.GetUserByUserId:output_type -> identity.GetUserByUserIdResponse
	7,  // 11: identity.IdentityService.Health:output_type -> identity.HealthResponse
	8,  // [8:12] is the sub-list for method output_type
	4,  // [4:8] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_identity_proto_init() }
func file_identity_proto_init() {
	if File_identity_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_identity_proto_rawDesc), len(file_identity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_identity_proto_goTypes,
		DependencyIndexes: file_identity_proto_depIdxs,
		MessageInfos:      file_identity_proto_msgTypes,
	}.Build()
	File_identity_proto = out.File
	file_identity_proto_goTypes = nil
	file_identity_proto_depIdxs = nil
}
