version: "3.9"

services:

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "19090:9090"

  calculation-service:
    build: ./services/calculation
    env_file:
      - ./services/calculation/.env