{
 "title": "Promtail Monitoring",
 "description": "Monitor Promtail metrics and logs",
 "tags": [ "promtail" ],
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource Loki", "query": "loki" },
   {
    "name": "label_name",
    "label": "Label Name",
    "query": {}
   },
   {
    "name": "label_value",
    "label": "Label Value",
    "query": {}
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(promtail_build_info,job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {}
   },
   { "name": "datasourceProm", "label": "Datasource Prometheus", "query": "prometheus" },
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,3m,5m,10m,30m" },
   { "name": "filter", "label": "LogQL Filter" }
  ]
 },
 "panels": [
  { "title": "Promtail - Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "DEBUG Log Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by(instance) (count_over_time({$label_name=~\"$label_value\", job=~\"$job\", instance=~\"$instance\"} | logfmt | level=\"debug\" | __error__=\"\" [$__range]))"
    }
   ]
  },
  {
   "title": "INFO Log Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (instance) (\n  count_over_time({ $label_name=~\"$label_value\" } | logfmt | level=\"info\" | __error__=\"\" [$__range])\n)"
    }
   ]
  },
  {
   "title": "WARN Log Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (instance) (\n  count_over_time({ $label_name=~\"$label_value\" } | logfmt | level=\"warn\" | __error__=\"\" [$__range])\n)"
    }
   ]
  },
  {
   "title": "ERROR Log Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (instance) (\n  count_over_time({ $label_name=~\"$label_value\" } | logfmt | level=\"error\" | __error__=\"\" [$__range])\n)"
    }
   ]
  },
  {
   "title": "Promtail Log Lines",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum by (level)(\n  count_over_time({ $label_name=~\"$label_value\" } | logfmt | level=~\"(debug|info|warn|error)\" | __error__=\"\" [$__range])\n)\n"
    }
   ]
  },
  {
   "title": "Promtail Log in bytes",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "direction": "backward",
     "expr": "sum(\n  bytes_over_time({ $label_name=~\"$label_value\" } | __error__=\"\" [$__range])\n)"
    }
   ]
  },
  {
   "title": "Promtail Version",
   "type": "stat",
   "description": "Deployed Promtail Version",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "promtail_build_info{job=~\"$job\", instance=~\"$instance.*\"} ",
     "legendFormat": "{{version}}"
    }
   ]
  },
  {
   "title": "Active Files",
   "type": "stat",
   "description": "Number of active files.",
   "gridPos": { "h": 3, "w": 2, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(promtail_files_active{job=\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Current Sent Bytes",
   "type": "stat",
   "description": "Current number of bytes sent. ( Real Time )",
   "gridPos": { "h": 3, "w": 3, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(promtail_sent_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Promtail Recent Logs",
   "type": "logs",
   "description": "Use LogQL Filter to filter information.",
   "gridPos": { "h": 12, "w": 22, "x": 0, "y": 4 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{ $label_name=~\"$label_value\" } | __error__=\"\" | logfmt | level=\"debug\" |= \"$filter\" | line_format `➡️ 🔵 {{regexReplaceAll \"level=debug|ts=[^\\\\s]+\\\\s\" __line__ \"$1\" | trim  }}`"
    },
    {
     "direction": "backward",
     "expr": "{ $label_name=~\"$label_value\" } | __error__=\"\" | logfmt | level=\"info\" |= \"$filter\" | line_format `➡️ 🟢 {{regexReplaceAll \"level=info|ts=[^\\\\s]+\\\\s\" __line__ \"$1\" | trim }}`"
    },
    {
     "direction": "backward",
     "expr": "{ $label_name=~\"$label_value\" } | __error__=\"\" | logfmt | level=\"warn\" |= \"$filter\" | line_format `➡️ 🟡 {{regexReplaceAll \"level=warn|ts=[^\\\\s]+\\\\s\" __line__ \"$1\" | trim  }}`"
    },
    {
     "direction": "backward",
     "expr": "{ $label_name=~\"$label_value\" } | __error__=\"\" | logfmt | level=\"error\" |= \"$filter\" | line_format `➡️ 🔴 {{regexReplaceAll \"level=error|ts=[^\\\\s]+\\\\s\" __line__ \"$1\" | trim  }}`"
    }
   ]
  },
  {
   "title": "Error Requests and Logs Count - Overtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * sum(rate(promtail_request_duration_seconds_count{job=\"$job\", instance=~\"$instance\", status_code=~\"5.*\"}[$interval])) \n    by (job, instance)\n  / sum(rate(promtail_request_duration_seconds_count{job=\"$job\", instance=~\"$instance\"}[$interval])) \n    by (job, instance)\n",
     "legendFormat": "Error Requests"
    },
    {
     "direction": "backward",
     "expr": "sum by (level) (\n  count_over_time({ $label_name=~\"$label_value\" } | logfmt | level=\"warn\" | __error__=\"\" [$__range])\n)\n",
     "legendFormat": "Warning Logs Lines"
    },
    {
     "direction": "backward",
     "expr": "sum by (level) (\n  count_over_time({ $label_name=~\"$label_value\" } | logfmt | level=\"error\" | __error__=\"\" [$__range])\n)\n",
     "legendFormat": "Error Logs Lines"
    }
   ]
  },
  { "title": "Promtail Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Read Bytes - Overtime",
   "type": "timeseries",
   "description": "Number of bytes read. - Overtime",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(promtail_read_bytes_total{job=\"$job\", instance=~\"$instance\"}[$interval]))\n",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Read Bytes - Details",
   "type": "table",
   "gridPos": { "h": 12, "w": 10, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "promtail_read_bytes_total{job=\"$job\", instance=~\"$instance\"}"
    },
    {
     "expr": "rate(promtail_read_bytes_total{job=\"$job\", instance=~\"$instance\"}[$interval])"
    },
    {
     "expr": "rate(promtail_read_lines_total{job=\"$job\", instance=~\"$instance\"}[$interval])"
    },
    {
     "expr": "increase(promtail_read_bytes_total{job=\"$job\", instance=~\"$instance\"}[24h])"
    }
   ]
  },
  {
   "title": "Encoded and Send Bytes - Overtime",
   "type": "timeseries",
   "description": "- Encoded: Number of bytes encoded and ready to send.\n- Send: Number of bytes sent. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(promtail_encoded_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "Encoded Bytes"
    },
    {
     "expr": "rate(promtail_sent_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "Send Bytes"
    }
   ]
  },
  {
   "title": "Encoded and Send - Details",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(promtail_sent_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])"
    },
    {
     "expr": "increase(promtail_sent_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[24h])"
    },
    {
     "expr": "rate(promtail_encoded_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])"
    },
    {
     "expr": "increase(promtail_encoded_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[24h])"
    }
   ]
  },
  {
   "title": "Dropped Bytes - Overtime",
   "type": "timeseries",
   "description": "- Dropped Bytes: Number of bytes dropped because failed to be sent to the ingester after all retries.\n- Dropped Entries: Number of log entries dropped because failed to be sent to the ingester after all retries.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(promtail_dropped_bytes_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "Dropped Bytes - {{reason}}"
    },
    {
     "expr": "rate(promtail_dropped_entries_total{job=~\"$job\", instance=~\"$instance.*\"}[$interval])",
     "legendFormat": "Dropped Entries - {{reason}}"
    }
   ]
  },
  {
   "title": "Request Latency - 99th Percentile Latency",
   "type": "timeseries",
   "description": "99th percentile latency",
   "gridPos": { "h": 8, "w": 10, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(promtail_request_duration_seconds_bucket{job=~\"$job\", instance=~\"$instance.*\"}[5m])) by (le))",
     "legendFormat": "Request Latency"
    }
   ]
  }
 ]
}