// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: calculation/calculation.proto

package calcpb

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Money struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Amount        int64                  `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency      string                 `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Money) Reset() {
	*x = Money{}
	mi := &file_calculation_calculation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Money) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Money) ProtoMessage() {}

func (x *Money) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_calculation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Money.ProtoReflect.Descriptor instead.
func (*Money) Descriptor() ([]byte, []int) {
	return file_calculation_calculation_proto_rawDescGZIP(), []int{0}
}

func (x *Money) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Money) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type Participant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Participant) Reset() {
	*x = Participant{}
	mi := &file_calculation_calculation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Participant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Participant) ProtoMessage() {}

func (x *Participant) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_calculation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Participant.ProtoReflect.Descriptor instead.
func (*Participant) Descriptor() ([]byte, []int) {
	return file_calculation_calculation_proto_rawDescGZIP(), []int{1}
}

func (x *Participant) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type Expense struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	AuthorId      string                 `protobuf:"bytes,2,opt,name=author_id,json=authorId,proto3" json:"author_id,omitempty"`
	Cost          *Money                 `protobuf:"bytes,3,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Expense) Reset() {
	*x = Expense{}
	mi := &file_calculation_calculation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Expense) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Expense) ProtoMessage() {}

func (x *Expense) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_calculation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Expense.ProtoReflect.Descriptor instead.
func (*Expense) Descriptor() ([]byte, []int) {
	return file_calculation_calculation_proto_rawDescGZIP(), []int{2}
}

func (x *Expense) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Expense) GetAuthorId() string {
	if x != nil {
		return x.AuthorId
	}
	return ""
}

func (x *Expense) GetCost() *Money {
	if x != nil {
		return x.Cost
	}
	return nil
}

type Intent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PayerId       string                 `protobuf:"bytes,1,opt,name=payer_id,json=payerId,proto3" json:"payer_id,omitempty"`
	PayeeId       string                 `protobuf:"bytes,2,opt,name=payee_id,json=payeeId,proto3" json:"payee_id,omitempty"`
	Amount        *Money                 `protobuf:"bytes,3,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Intent) Reset() {
	*x = Intent{}
	mi := &file_calculation_calculation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Intent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Intent) ProtoMessage() {}

func (x *Intent) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_calculation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Intent.ProtoReflect.Descriptor instead.
func (*Intent) Descriptor() ([]byte, []int) {
	return file_calculation_calculation_proto_rawDescGZIP(), []int{3}
}

func (x *Intent) GetPayerId() string {
	if x != nil {
		return x.PayerId
	}
	return ""
}

func (x *Intent) GetPayeeId() string {
	if x != nil {
		return x.PayeeId
	}
	return ""
}

func (x *Intent) GetAmount() *Money {
	if x != nil {
		return x.Amount
	}
	return nil
}

type CalcRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	Participants  []*Participant         `protobuf:"bytes,2,rep,name=participants,proto3" json:"participants,omitempty"`
	Expenses      []*Expense             `protobuf:"bytes,3,rep,name=expenses,proto3" json:"expenses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcRequest) Reset() {
	*x = CalcRequest{}
	mi := &file_calculation_calculation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcRequest) ProtoMessage() {}

func (x *CalcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_calculation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcRequest.ProtoReflect.Descriptor instead.
func (*CalcRequest) Descriptor() ([]byte, []int) {
	return file_calculation_calculation_proto_rawDescGZIP(), []int{4}
}

func (x *CalcRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *CalcRequest) GetParticipants() []*Participant {
	if x != nil {
		return x.Participants
	}
	return nil
}

func (x *CalcRequest) GetExpenses() []*Expense {
	if x != nil {
		return x.Expenses
	}
	return nil
}

type CalcResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	Intents       []*Intent              `protobuf:"bytes,2,rep,name=intents,proto3" json:"intents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalcResponse) Reset() {
	*x = CalcResponse{}
	mi := &file_calculation_calculation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalcResponse) ProtoMessage() {}

func (x *CalcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_calculation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalcResponse.ProtoReflect.Descriptor instead.
func (*CalcResponse) Descriptor() ([]byte, []int) {
	return file_calculation_calculation_proto_rawDescGZIP(), []int{5}
}

func (x *CalcResponse) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *CalcResponse) GetIntents() []*Intent {
	if x != nil {
		return x.Intents
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_calculation_calculation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_calculation_calculation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_calculation_calculation_proto_rawDescGZIP(), []int{6}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_calculation_calculation_proto protoreflect.FileDescriptor

const file_calculation_calculation_proto_rawDesc = "" +
	"\n" +
	"\x1dcalculation/calculation.proto\x12\vcalculation\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1cgoogle/api/annotations.proto\x1a\x15google/api/http.proto\";\n" +
	"\x05Money\x12\x16\n" +
	"\x06amount\x18\x01 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x02 \x01(\tR\bcurrency\"&\n" +
	"\vParticipant\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"^\n" +
	"\aExpense\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tauthor_id\x18\x02 \x01(\tR\bauthorId\x12&\n" +
	"\x04cost\x18\x03 \x01(\v2\x12.calculation.MoneyR\x04cost\"j\n" +
	"\x06Intent\x12\x19\n" +
	"\bpayer_id\x18\x01 \x01(\tR\apayerId\x12\x19\n" +
	"\bpayee_id\x18\x02 \x01(\tR\apayeeId\x12*\n" +
	"\x06amount\x18\x03 \x01(\v2\x12.calculation.MoneyR\x06amount\"\x9e\x01\n" +
	"\vCalcRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\x12<\n" +
	"\fparticipants\x18\x02 \x03(\v2\x18.calculation.ParticipantR\fparticipants\x120\n" +
	"\bexpenses\x18\x03 \x03(\v2\x14.calculation.ExpenseR\bexpenses\"^\n" +
	"\fCalcResponse\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\x12-\n" +
	"\aintents\x18\x02 \x03(\v2\x13.calculation.IntentR\aintents\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xe8\x01\n" +
	"\x12CalculationService\x12y\n" +
	"\x15CalculateDistribution\x12\x18.calculation.CalcRequest\x1a\x19.calculation.CalcResponse\"+\x82\xd3\xe4\x93\x02%:\x01*\" /internal/calculation/distribute\x12W\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x1b.calculation.HealthResponse\"\x18\x82\xd3\xe4\x93\x02\x12\x12\x10/internal/healthBTZRgithub.com/nikitadev-work/SyncBuyProject/services/calculation/proto-codegen;calcpbb\x06proto3"

var (
	file_calculation_calculation_proto_rawDescOnce sync.Once
	file_calculation_calculation_proto_rawDescData []byte
)

func file_calculation_calculation_proto_rawDescGZIP() []byte {
	file_calculation_calculation_proto_rawDescOnce.Do(func() {
		file_calculation_calculation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_calculation_calculation_proto_rawDesc), len(file_calculation_calculation_proto_rawDesc)))
	})
	return file_calculation_calculation_proto_rawDescData
}

var file_calculation_calculation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_calculation_calculation_proto_goTypes = []any{
	(*Money)(nil),          // 0: calculation.Money
	(*Participant)(nil),    // 1: calculation.Participant
	(*Expense)(nil),        // 2: calculation.Expense
	(*Intent)(nil),         // 3: calculation.Intent
	(*CalcRequest)(nil),    // 4: calculation.CalcRequest
	(*CalcResponse)(nil),   // 5: calculation.CalcResponse
	(*HealthResponse)(nil), // 6: calculation.HealthResponse
	(*emptypb.Empty)(nil),  // 7: google.protobuf.Empty
}
var file_calculation_calculation_proto_depIdxs = []int32{
	0, // 0: calculation.Expense.cost:type_name -> calculation.Money
	0, // 1: calculation.Intent.amount:type_name -> calculation.Money
	1, // 2: calculation.CalcRequest.participants:type_name -> calculation.Participant
	2, // 3: calculation.CalcRequest.expenses:type_name -> calculation.Expense
	3, // 4: calculation.CalcResponse.intents:type_name -> calculation.Intent
	4, // 5: calculation.CalculationService.CalculateDistribution:input_type -> calculation.CalcRequest
	7, // 6: calculation.CalculationService.Health:input_type -> google.protobuf.Empty
	5, // 7: calculation.CalculationService.CalculateDistribution:output_type -> calculation.CalcResponse
	6, // 8: calculation.CalculationService.Health:output_type -> calculation.HealthResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_calculation_calculation_proto_init() }
func file_calculation_calculation_proto_init() {
	if File_calculation_calculation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_calculation_calculation_proto_rawDesc), len(file_calculation_calculation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_calculation_calculation_proto_goTypes,
		DependencyIndexes: file_calculation_calculation_proto_depIdxs,
		MessageInfos:      file_calculation_calculation_proto_msgTypes,
	}.Build()
	File_calculation_calculation_proto = out.File
	file_calculation_calculation_proto_goTypes = nil
	file_calculation_calculation_proto_depIdxs = nil
}
