scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'promtail'
    static_configs:
      - targets: ['promtail:9080']

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']

  - job_name: 'identity-service'
    static_configs:
      - targets: ['identity-service:8080']

  - job_name: 'notifications-service'
    static_configs:
      - targets: ['notifications-service:8080']

  - job_name: 'payments-service'
    static_configs:
      - targets: ['payments-service:8080']

  - job_name: 'purchase-service'
    static_configs:
      - targets: ['purchase-service:8080']

  - job_name: 'reports-service'
    static_configs:
      - targets: ['reports-service:8080']
  
  - job_name: 'calculation-service'
    static_configs:
      - targets: ['calculation-service:8080']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']