// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: purchase.proto

package purchasepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PurchaseService_CreatePurchase_FullMethodName               = "/purchase.PurchaseService/CreatePurchase"
	PurchaseService_GetPurchase_FullMethodName                  = "/purchase.PurchaseService/GetPurchase"
	PurchaseService_CreateInvite_FullMethodName                 = "/purchase.PurchaseService/CreateInvite"
	PurchaseService_JoinByInvite_FullMethodName                 = "/purchase.PurchaseService/JoinByInvite"
	PurchaseService_RemoveParticipant_FullMethodName            = "/purchase.PurchaseService/RemoveParticipant"
	PurchaseService_ListParticipantsByPurchaseId_FullMethodName = "/purchase.PurchaseService/ListParticipantsByPurchaseId"
	PurchaseService_CreateTask_FullMethodName                   = "/purchase.PurchaseService/CreateTask"
	PurchaseService_TakeTask_FullMethodName                     = "/purchase.PurchaseService/TakeTask"
	PurchaseService_DeleteTask_FullMethodName                   = "/purchase.PurchaseService/DeleteTask"
	PurchaseService_ListTasksByPurchaseId_FullMethodName        = "/purchase.PurchaseService/ListTasksByPurchaseId"
	PurchaseService_MarkTaskAsDone_FullMethodName               = "/purchase.PurchaseService/MarkTaskAsDone"
	PurchaseService_LockPurchase_FullMethodName                 = "/purchase.PurchaseService/LockPurchase"
	PurchaseService_UnlockPurchase_FullMethodName               = "/purchase.PurchaseService/UnlockPurchase"
	PurchaseService_GetSnapshot_FullMethodName                  = "/purchase.PurchaseService/GetSnapshot"
	PurchaseService_MarkSettlementInitiated_FullMethodName      = "/purchase.PurchaseService/MarkSettlementInitiated"
	PurchaseService_FinishPurchase_FullMethodName               = "/purchase.PurchaseService/FinishPurchase"
	PurchaseService_Health_FullMethodName                       = "/purchase.PurchaseService/Health"
)

// PurchaseServiceClient is the client API for PurchaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PurchaseServiceClient interface {
	// Purchase
	CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error)
	GetPurchase(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*GetPurchaseResponse, error)
	// Participant
	CreateInvite(ctx context.Context, in *CreateInviteRequest, opts ...grpc.CallOption) (*CreateInviteResponse, error)
	JoinByInvite(ctx context.Context, in *JoinByInviteRequest, opts ...grpc.CallOption) (*JoinByInviteResponse, error)
	RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*RemoveParticipantResponse, error)
	ListParticipantsByPurchaseId(ctx context.Context, in *ListParticipantsByPurchaseIdRequest, opts ...grpc.CallOption) (*ListParticipantsByPurchaseIdResponse, error)
	// Task
	CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error)
	TakeTask(ctx context.Context, in *TakeTaskRequest, opts ...grpc.CallOption) (*TakeTaskResponse, error)
	DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error)
	ListTasksByPurchaseId(ctx context.Context, in *ListTasksByPurchaseIdRequest, opts ...grpc.CallOption) (*ListTasksByPurchaseIdResponse, error)
	MarkTaskAsDone(ctx context.Context, in *MarkTaskAsDoneRequest, opts ...grpc.CallOption) (*MarkTaskAsDoneResponse, error)
	// Status
	LockPurchase(ctx context.Context, in *LockPurchaseRequest, opts ...grpc.CallOption) (*LockPurchaseResponse, error)
	UnlockPurchase(ctx context.Context, in *UnlockPurchaseRequest, opts ...grpc.CallOption) (*UnlockPurchaseResponse, error)
	GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error)
	MarkSettlementInitiated(ctx context.Context, in *MarkSettlementInitiatedRequest, opts ...grpc.CallOption) (*MarkSettlementInitiatedResponse, error)
	FinishPurchase(ctx context.Context, in *FinishPurchaseRequest, opts ...grpc.CallOption) (*FinishPurchaseResponse, error)
	// Health
	Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error)
}

type purchaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPurchaseServiceClient(cc grpc.ClientConnInterface) PurchaseServiceClient {
	return &purchaseServiceClient{cc}
}

func (c *purchaseServiceClient) CreatePurchase(ctx context.Context, in *CreatePurchaseRequest, opts ...grpc.CallOption) (*CreatePurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreatePurchaseResponse)
	err := c.cc.Invoke(ctx, PurchaseService_CreatePurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) GetPurchase(ctx context.Context, in *GetPurchaseRequest, opts ...grpc.CallOption) (*GetPurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPurchaseResponse)
	err := c.cc.Invoke(ctx, PurchaseService_GetPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) CreateInvite(ctx context.Context, in *CreateInviteRequest, opts ...grpc.CallOption) (*CreateInviteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInviteResponse)
	err := c.cc.Invoke(ctx, PurchaseService_CreateInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) JoinByInvite(ctx context.Context, in *JoinByInviteRequest, opts ...grpc.CallOption) (*JoinByInviteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinByInviteResponse)
	err := c.cc.Invoke(ctx, PurchaseService_JoinByInvite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) RemoveParticipant(ctx context.Context, in *RemoveParticipantRequest, opts ...grpc.CallOption) (*RemoveParticipantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveParticipantResponse)
	err := c.cc.Invoke(ctx, PurchaseService_RemoveParticipant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) ListParticipantsByPurchaseId(ctx context.Context, in *ListParticipantsByPurchaseIdRequest, opts ...grpc.CallOption) (*ListParticipantsByPurchaseIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListParticipantsByPurchaseIdResponse)
	err := c.cc.Invoke(ctx, PurchaseService_ListParticipantsByPurchaseId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) CreateTask(ctx context.Context, in *CreateTaskRequest, opts ...grpc.CallOption) (*CreateTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTaskResponse)
	err := c.cc.Invoke(ctx, PurchaseService_CreateTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) TakeTask(ctx context.Context, in *TakeTaskRequest, opts ...grpc.CallOption) (*TakeTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TakeTaskResponse)
	err := c.cc.Invoke(ctx, PurchaseService_TakeTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) DeleteTask(ctx context.Context, in *DeleteTaskRequest, opts ...grpc.CallOption) (*DeleteTaskResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteTaskResponse)
	err := c.cc.Invoke(ctx, PurchaseService_DeleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) ListTasksByPurchaseId(ctx context.Context, in *ListTasksByPurchaseIdRequest, opts ...grpc.CallOption) (*ListTasksByPurchaseIdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTasksByPurchaseIdResponse)
	err := c.cc.Invoke(ctx, PurchaseService_ListTasksByPurchaseId_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) MarkTaskAsDone(ctx context.Context, in *MarkTaskAsDoneRequest, opts ...grpc.CallOption) (*MarkTaskAsDoneResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkTaskAsDoneResponse)
	err := c.cc.Invoke(ctx, PurchaseService_MarkTaskAsDone_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) LockPurchase(ctx context.Context, in *LockPurchaseRequest, opts ...grpc.CallOption) (*LockPurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockPurchaseResponse)
	err := c.cc.Invoke(ctx, PurchaseService_LockPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) UnlockPurchase(ctx context.Context, in *UnlockPurchaseRequest, opts ...grpc.CallOption) (*UnlockPurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnlockPurchaseResponse)
	err := c.cc.Invoke(ctx, PurchaseService_UnlockPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) GetSnapshot(ctx context.Context, in *GetSnapshotRequest, opts ...grpc.CallOption) (*GetSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSnapshotResponse)
	err := c.cc.Invoke(ctx, PurchaseService_GetSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) MarkSettlementInitiated(ctx context.Context, in *MarkSettlementInitiatedRequest, opts ...grpc.CallOption) (*MarkSettlementInitiatedResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MarkSettlementInitiatedResponse)
	err := c.cc.Invoke(ctx, PurchaseService_MarkSettlementInitiated_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) FinishPurchase(ctx context.Context, in *FinishPurchaseRequest, opts ...grpc.CallOption) (*FinishPurchaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinishPurchaseResponse)
	err := c.cc.Invoke(ctx, PurchaseService_FinishPurchase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *purchaseServiceClient) Health(ctx context.Context, in *HealthRequest, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, PurchaseService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PurchaseServiceServer is the server API for PurchaseService service.
// All implementations must embed UnimplementedPurchaseServiceServer
// for forward compatibility.
type PurchaseServiceServer interface {
	// Purchase
	CreatePurchase(context.Context, *CreatePurchaseRequest) (*CreatePurchaseResponse, error)
	GetPurchase(context.Context, *GetPurchaseRequest) (*GetPurchaseResponse, error)
	// Participant
	CreateInvite(context.Context, *CreateInviteRequest) (*CreateInviteResponse, error)
	JoinByInvite(context.Context, *JoinByInviteRequest) (*JoinByInviteResponse, error)
	RemoveParticipant(context.Context, *RemoveParticipantRequest) (*RemoveParticipantResponse, error)
	ListParticipantsByPurchaseId(context.Context, *ListParticipantsByPurchaseIdRequest) (*ListParticipantsByPurchaseIdResponse, error)
	// Task
	CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
	TakeTask(context.Context, *TakeTaskRequest) (*TakeTaskResponse, error)
	DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error)
	ListTasksByPurchaseId(context.Context, *ListTasksByPurchaseIdRequest) (*ListTasksByPurchaseIdResponse, error)
	MarkTaskAsDone(context.Context, *MarkTaskAsDoneRequest) (*MarkTaskAsDoneResponse, error)
	// Status
	LockPurchase(context.Context, *LockPurchaseRequest) (*LockPurchaseResponse, error)
	UnlockPurchase(context.Context, *UnlockPurchaseRequest) (*UnlockPurchaseResponse, error)
	GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error)
	MarkSettlementInitiated(context.Context, *MarkSettlementInitiatedRequest) (*MarkSettlementInitiatedResponse, error)
	FinishPurchase(context.Context, *FinishPurchaseRequest) (*FinishPurchaseResponse, error)
	// Health
	Health(context.Context, *HealthRequest) (*HealthResponse, error)
	mustEmbedUnimplementedPurchaseServiceServer()
}

// UnimplementedPurchaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPurchaseServiceServer struct{}

func (UnimplementedPurchaseServiceServer) CreatePurchase(context.Context, *CreatePurchaseRequest) (*CreatePurchaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreatePurchase not implemented")
}
func (UnimplementedPurchaseServiceServer) GetPurchase(context.Context, *GetPurchaseRequest) (*GetPurchaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPurchase not implemented")
}
func (UnimplementedPurchaseServiceServer) CreateInvite(context.Context, *CreateInviteRequest) (*CreateInviteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateInvite not implemented")
}
func (UnimplementedPurchaseServiceServer) JoinByInvite(context.Context, *JoinByInviteRequest) (*JoinByInviteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method JoinByInvite not implemented")
}
func (UnimplementedPurchaseServiceServer) RemoveParticipant(context.Context, *RemoveParticipantRequest) (*RemoveParticipantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveParticipant not implemented")
}
func (UnimplementedPurchaseServiceServer) ListParticipantsByPurchaseId(context.Context, *ListParticipantsByPurchaseIdRequest) (*ListParticipantsByPurchaseIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListParticipantsByPurchaseId not implemented")
}
func (UnimplementedPurchaseServiceServer) CreateTask(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTask not implemented")
}
func (UnimplementedPurchaseServiceServer) TakeTask(context.Context, *TakeTaskRequest) (*TakeTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TakeTask not implemented")
}
func (UnimplementedPurchaseServiceServer) DeleteTask(context.Context, *DeleteTaskRequest) (*DeleteTaskResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTask not implemented")
}
func (UnimplementedPurchaseServiceServer) ListTasksByPurchaseId(context.Context, *ListTasksByPurchaseIdRequest) (*ListTasksByPurchaseIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTasksByPurchaseId not implemented")
}
func (UnimplementedPurchaseServiceServer) MarkTaskAsDone(context.Context, *MarkTaskAsDoneRequest) (*MarkTaskAsDoneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkTaskAsDone not implemented")
}
func (UnimplementedPurchaseServiceServer) LockPurchase(context.Context, *LockPurchaseRequest) (*LockPurchaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LockPurchase not implemented")
}
func (UnimplementedPurchaseServiceServer) UnlockPurchase(context.Context, *UnlockPurchaseRequest) (*UnlockPurchaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnlockPurchase not implemented")
}
func (UnimplementedPurchaseServiceServer) GetSnapshot(context.Context, *GetSnapshotRequest) (*GetSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSnapshot not implemented")
}
func (UnimplementedPurchaseServiceServer) MarkSettlementInitiated(context.Context, *MarkSettlementInitiatedRequest) (*MarkSettlementInitiatedResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MarkSettlementInitiated not implemented")
}
func (UnimplementedPurchaseServiceServer) FinishPurchase(context.Context, *FinishPurchaseRequest) (*FinishPurchaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishPurchase not implemented")
}
func (UnimplementedPurchaseServiceServer) Health(context.Context, *HealthRequest) (*HealthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedPurchaseServiceServer) mustEmbedUnimplementedPurchaseServiceServer() {}
func (UnimplementedPurchaseServiceServer) testEmbeddedByValue()                         {}

// UnsafePurchaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PurchaseServiceServer will
// result in compilation errors.
type UnsafePurchaseServiceServer interface {
	mustEmbedUnimplementedPurchaseServiceServer()
}

func RegisterPurchaseServiceServer(s grpc.ServiceRegistrar, srv PurchaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedPurchaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PurchaseService_ServiceDesc, srv)
}

func _PurchaseService_CreatePurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreatePurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).CreatePurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_CreatePurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).CreatePurchase(ctx, req.(*CreatePurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_GetPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).GetPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_GetPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).GetPurchase(ctx, req.(*GetPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_CreateInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).CreateInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_CreateInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).CreateInvite(ctx, req.(*CreateInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_JoinByInvite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinByInviteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).JoinByInvite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_JoinByInvite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).JoinByInvite(ctx, req.(*JoinByInviteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_RemoveParticipant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveParticipantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).RemoveParticipant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_RemoveParticipant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).RemoveParticipant(ctx, req.(*RemoveParticipantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_ListParticipantsByPurchaseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParticipantsByPurchaseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).ListParticipantsByPurchaseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_ListParticipantsByPurchaseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).ListParticipantsByPurchaseId(ctx, req.(*ListParticipantsByPurchaseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_CreateTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).CreateTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_CreateTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).CreateTask(ctx, req.(*CreateTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_TakeTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TakeTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).TakeTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_TakeTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).TakeTask(ctx, req.(*TakeTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_DeleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).DeleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_DeleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).DeleteTask(ctx, req.(*DeleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_ListTasksByPurchaseId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTasksByPurchaseIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).ListTasksByPurchaseId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_ListTasksByPurchaseId_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).ListTasksByPurchaseId(ctx, req.(*ListTasksByPurchaseIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_MarkTaskAsDone_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkTaskAsDoneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).MarkTaskAsDone(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_MarkTaskAsDone_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).MarkTaskAsDone(ctx, req.(*MarkTaskAsDoneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_LockPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).LockPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_LockPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).LockPurchase(ctx, req.(*LockPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_UnlockPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnlockPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).UnlockPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_UnlockPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).UnlockPurchase(ctx, req.(*UnlockPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_GetSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).GetSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_GetSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).GetSnapshot(ctx, req.(*GetSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_MarkSettlementInitiated_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MarkSettlementInitiatedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).MarkSettlementInitiated(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_MarkSettlementInitiated_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).MarkSettlementInitiated(ctx, req.(*MarkSettlementInitiatedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_FinishPurchase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishPurchaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).FinishPurchase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_FinishPurchase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).FinishPurchase(ctx, req.(*FinishPurchaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PurchaseService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PurchaseServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PurchaseService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PurchaseServiceServer).Health(ctx, req.(*HealthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PurchaseService_ServiceDesc is the grpc.ServiceDesc for PurchaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PurchaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "purchase.PurchaseService",
	HandlerType: (*PurchaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreatePurchase",
			Handler:    _PurchaseService_CreatePurchase_Handler,
		},
		{
			MethodName: "GetPurchase",
			Handler:    _PurchaseService_GetPurchase_Handler,
		},
		{
			MethodName: "CreateInvite",
			Handler:    _PurchaseService_CreateInvite_Handler,
		},
		{
			MethodName: "JoinByInvite",
			Handler:    _PurchaseService_JoinByInvite_Handler,
		},
		{
			MethodName: "RemoveParticipant",
			Handler:    _PurchaseService_RemoveParticipant_Handler,
		},
		{
			MethodName: "ListParticipantsByPurchaseId",
			Handler:    _PurchaseService_ListParticipantsByPurchaseId_Handler,
		},
		{
			MethodName: "CreateTask",
			Handler:    _PurchaseService_CreateTask_Handler,
		},
		{
			MethodName: "TakeTask",
			Handler:    _PurchaseService_TakeTask_Handler,
		},
		{
			MethodName: "DeleteTask",
			Handler:    _PurchaseService_DeleteTask_Handler,
		},
		{
			MethodName: "ListTasksByPurchaseId",
			Handler:    _PurchaseService_ListTasksByPurchaseId_Handler,
		},
		{
			MethodName: "MarkTaskAsDone",
			Handler:    _PurchaseService_MarkTaskAsDone_Handler,
		},
		{
			MethodName: "LockPurchase",
			Handler:    _PurchaseService_LockPurchase_Handler,
		},
		{
			MethodName: "UnlockPurchase",
			Handler:    _PurchaseService_UnlockPurchase_Handler,
		},
		{
			MethodName: "GetSnapshot",
			Handler:    _PurchaseService_GetSnapshot_Handler,
		},
		{
			MethodName: "MarkSettlementInitiated",
			Handler:    _PurchaseService_MarkSettlementInitiated_Handler,
		},
		{
			MethodName: "FinishPurchase",
			Handler:    _PurchaseService_FinishPurchase_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _PurchaseService_Health_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "purchase.proto",
}
