// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: purchase.proto

package purchasepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Purchase struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Id                    string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title                 string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description           string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Currency              string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	SettlementInitiatedAt *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=settlement_initiated_at,json=settlementInitiatedAt,proto3" json:"settlement_initiated_at,omitempty"`
	Status                string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	LockedAt              *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=locked_at,json=lockedAt,proto3" json:"locked_at,omitempty"`
	FinishedAt            *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=finished_at,json=finishedAt,proto3" json:"finished_at,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Purchase) Reset() {
	*x = Purchase{}
	mi := &file_purchase_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Purchase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Purchase) ProtoMessage() {}

func (x *Purchase) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Purchase.ProtoReflect.Descriptor instead.
func (*Purchase) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{0}
}

func (x *Purchase) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Purchase) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Purchase) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Purchase) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Purchase) GetSettlementInitiatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.SettlementInitiatedAt
	}
	return nil
}

func (x *Purchase) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Purchase) GetLockedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LockedAt
	}
	return nil
}

func (x *Purchase) GetFinishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.FinishedAt
	}
	return nil
}

type Task struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title          string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	PurchaseId     string                 `protobuf:"bytes,4,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	AuthorUserId   string                 `protobuf:"bytes,5,opt,name=author_user_id,json=authorUserId,proto3" json:"author_user_id,omitempty"`
	ExecutorUserId string                 `protobuf:"bytes,6,opt,name=executor_user_id,json=executorUserId,proto3" json:"executor_user_id,omitempty"`
	Done           bool                   `protobuf:"varint,7,opt,name=done,proto3" json:"done,omitempty"`
	Amount         int64                  `protobuf:"varint,8,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_purchase_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{1}
}

func (x *Task) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Task) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Task) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Task) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *Task) GetAuthorUserId() string {
	if x != nil {
		return x.AuthorUserId
	}
	return ""
}

func (x *Task) GetExecutorUserId() string {
	if x != nil {
		return x.ExecutorUserId
	}
	return ""
}

func (x *Task) GetDone() bool {
	if x != nil {
		return x.Done
	}
	return false
}

func (x *Task) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type Snapshot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId         string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	PurchaseTitle      string                 `protobuf:"bytes,2,opt,name=purchase_title,json=purchaseTitle,proto3" json:"purchase_title,omitempty"`
	Currency           string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	Tasks              []*Task                `protobuf:"bytes,4,rep,name=tasks,proto3" json:"tasks,omitempty"`
	ParticipantUserIds []string               `protobuf:"bytes,5,rep,name=participant_user_ids,json=participantUserIds,proto3" json:"participant_user_ids,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Snapshot) Reset() {
	*x = Snapshot{}
	mi := &file_purchase_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Snapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Snapshot) ProtoMessage() {}

func (x *Snapshot) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Snapshot.ProtoReflect.Descriptor instead.
func (*Snapshot) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{2}
}

func (x *Snapshot) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *Snapshot) GetPurchaseTitle() string {
	if x != nil {
		return x.PurchaseTitle
	}
	return ""
}

func (x *Snapshot) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *Snapshot) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

func (x *Snapshot) GetParticipantUserIds() []string {
	if x != nil {
		return x.ParticipantUserIds
	}
	return nil
}

type CreatePurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Currency      string                 `protobuf:"bytes,3,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePurchaseRequest) Reset() {
	*x = CreatePurchaseRequest{}
	mi := &file_purchase_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePurchaseRequest) ProtoMessage() {}

func (x *CreatePurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePurchaseRequest.ProtoReflect.Descriptor instead.
func (*CreatePurchaseRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{3}
}

func (x *CreatePurchaseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreatePurchaseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreatePurchaseRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type CreatePurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePurchaseResponse) Reset() {
	*x = CreatePurchaseResponse{}
	mi := &file_purchase_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePurchaseResponse) ProtoMessage() {}

func (x *CreatePurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePurchaseResponse.ProtoReflect.Descriptor instead.
func (*CreatePurchaseResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{4}
}

func (x *CreatePurchaseResponse) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type GetPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchaseRequest) Reset() {
	*x = GetPurchaseRequest{}
	mi := &file_purchase_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchaseRequest) ProtoMessage() {}

func (x *GetPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchaseRequest.ProtoReflect.Descriptor instead.
func (*GetPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{5}
}

func (x *GetPurchaseRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type GetPurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchase      *Purchase              `protobuf:"bytes,1,opt,name=purchase,proto3" json:"purchase,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPurchaseResponse) Reset() {
	*x = GetPurchaseResponse{}
	mi := &file_purchase_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPurchaseResponse) ProtoMessage() {}

func (x *GetPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPurchaseResponse.ProtoReflect.Descriptor instead.
func (*GetPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{6}
}

func (x *GetPurchaseResponse) GetPurchase() *Purchase {
	if x != nil {
		return x.Purchase
	}
	return nil
}

type ListPurchasesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPurchasesRequest) Reset() {
	*x = ListPurchasesRequest{}
	mi := &file_purchase_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPurchasesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPurchasesRequest) ProtoMessage() {}

func (x *ListPurchasesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPurchasesRequest.ProtoReflect.Descriptor instead.
func (*ListPurchasesRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{7}
}

func (x *ListPurchasesRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type ListPurchasesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Purchases     []*Purchase            `protobuf:"bytes,1,rep,name=purchases,proto3" json:"purchases,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPurchasesResponse) Reset() {
	*x = ListPurchasesResponse{}
	mi := &file_purchase_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPurchasesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPurchasesResponse) ProtoMessage() {}

func (x *ListPurchasesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPurchasesResponse.ProtoReflect.Descriptor instead.
func (*ListPurchasesResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{8}
}

func (x *ListPurchasesResponse) GetPurchases() []*Purchase {
	if x != nil {
		return x.Purchases
	}
	return nil
}

type CreateInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,3,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteRequest) Reset() {
	*x = CreateInviteRequest{}
	mi := &file_purchase_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteRequest) ProtoMessage() {}

func (x *CreateInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteRequest.ProtoReflect.Descriptor instead.
func (*CreateInviteRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{9}
}

func (x *CreateInviteRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type CreateInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateInviteResponse) Reset() {
	*x = CreateInviteResponse{}
	mi := &file_purchase_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInviteResponse) ProtoMessage() {}

func (x *CreateInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInviteResponse.ProtoReflect.Descriptor instead.
func (*CreateInviteResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{10}
}

func (x *CreateInviteResponse) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *CreateInviteResponse) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateInviteResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type JoinByInviteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinByInviteRequest) Reset() {
	*x = JoinByInviteRequest{}
	mi := &file_purchase_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinByInviteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinByInviteRequest) ProtoMessage() {}

func (x *JoinByInviteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinByInviteRequest.ProtoReflect.Descriptor instead.
func (*JoinByInviteRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{11}
}

func (x *JoinByInviteRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *JoinByInviteRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type JoinByInviteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinByInviteResponse) Reset() {
	*x = JoinByInviteResponse{}
	mi := &file_purchase_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinByInviteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinByInviteResponse) ProtoMessage() {}

func (x *JoinByInviteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinByInviteResponse.ProtoReflect.Descriptor instead.
func (*JoinByInviteResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{12}
}

func (x *JoinByInviteResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type RemoveParticipantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PurchaseId    string                 `protobuf:"bytes,2,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantRequest) Reset() {
	*x = RemoveParticipantRequest{}
	mi := &file_purchase_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantRequest) ProtoMessage() {}

func (x *RemoveParticipantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantRequest.ProtoReflect.Descriptor instead.
func (*RemoveParticipantRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{13}
}

func (x *RemoveParticipantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveParticipantRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type RemoveParticipantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveParticipantResponse) Reset() {
	*x = RemoveParticipantResponse{}
	mi := &file_purchase_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveParticipantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveParticipantResponse) ProtoMessage() {}

func (x *RemoveParticipantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveParticipantResponse.ProtoReflect.Descriptor instead.
func (*RemoveParticipantResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{14}
}

func (x *RemoveParticipantResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type ListParticipantsByPurchaseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParticipantsByPurchaseIdRequest) Reset() {
	*x = ListParticipantsByPurchaseIdRequest{}
	mi := &file_purchase_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParticipantsByPurchaseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParticipantsByPurchaseIdRequest) ProtoMessage() {}

func (x *ListParticipantsByPurchaseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParticipantsByPurchaseIdRequest.ProtoReflect.Descriptor instead.
func (*ListParticipantsByPurchaseIdRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{15}
}

func (x *ListParticipantsByPurchaseIdRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type ListParticipantsByPurchaseIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListParticipantsByPurchaseIdResponse) Reset() {
	*x = ListParticipantsByPurchaseIdResponse{}
	mi := &file_purchase_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListParticipantsByPurchaseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListParticipantsByPurchaseIdResponse) ProtoMessage() {}

func (x *ListParticipantsByPurchaseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListParticipantsByPurchaseIdResponse.ProtoReflect.Descriptor instead.
func (*ListParticipantsByPurchaseIdResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{16}
}

func (x *ListParticipantsByPurchaseIdResponse) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	PurchaseId    string                 `protobuf:"bytes,3,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	AuthorUserId  string                 `protobuf:"bytes,4,opt,name=author_user_id,json=authorUserId,proto3" json:"author_user_id,omitempty"`
	Amount        int64                  `protobuf:"varint,5,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_purchase_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{17}
}

func (x *CreateTaskRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateTaskRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateTaskRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

func (x *CreateTaskRequest) GetAuthorUserId() string {
	if x != nil {
		return x.AuthorUserId
	}
	return ""
}

func (x *CreateTaskRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_purchase_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{18}
}

func (x *CreateTaskResponse) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type TakeTaskRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	ExecutorUserId string                 `protobuf:"bytes,2,opt,name=executor_user_id,json=executorUserId,proto3" json:"executor_user_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TakeTaskRequest) Reset() {
	*x = TakeTaskRequest{}
	mi := &file_purchase_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeTaskRequest) ProtoMessage() {}

func (x *TakeTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeTaskRequest.ProtoReflect.Descriptor instead.
func (*TakeTaskRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{19}
}

func (x *TakeTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TakeTaskRequest) GetExecutorUserId() string {
	if x != nil {
		return x.ExecutorUserId
	}
	return ""
}

type TakeTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TakeTaskResponse) Reset() {
	*x = TakeTaskResponse{}
	mi := &file_purchase_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TakeTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TakeTaskResponse) ProtoMessage() {}

func (x *TakeTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TakeTaskResponse.ProtoReflect.Descriptor instead.
func (*TakeTaskResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{20}
}

func (x *TakeTaskResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type DeleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskRequest) Reset() {
	*x = DeleteTaskRequest{}
	mi := &file_purchase_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskRequest) ProtoMessage() {}

func (x *DeleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskRequest.ProtoReflect.Descriptor instead.
func (*DeleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{21}
}

func (x *DeleteTaskRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type DeleteTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteTaskResponse) Reset() {
	*x = DeleteTaskResponse{}
	mi := &file_purchase_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTaskResponse) ProtoMessage() {}

func (x *DeleteTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTaskResponse.ProtoReflect.Descriptor instead.
func (*DeleteTaskResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{22}
}

func (x *DeleteTaskResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type ListTasksByPurchaseIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksByPurchaseIdRequest) Reset() {
	*x = ListTasksByPurchaseIdRequest{}
	mi := &file_purchase_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksByPurchaseIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksByPurchaseIdRequest) ProtoMessage() {}

func (x *ListTasksByPurchaseIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksByPurchaseIdRequest.ProtoReflect.Descriptor instead.
func (*ListTasksByPurchaseIdRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{23}
}

func (x *ListTasksByPurchaseIdRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type ListTasksByPurchaseIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tasks         []*Task                `protobuf:"bytes,1,rep,name=tasks,proto3" json:"tasks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTasksByPurchaseIdResponse) Reset() {
	*x = ListTasksByPurchaseIdResponse{}
	mi := &file_purchase_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTasksByPurchaseIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTasksByPurchaseIdResponse) ProtoMessage() {}

func (x *ListTasksByPurchaseIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTasksByPurchaseIdResponse.ProtoReflect.Descriptor instead.
func (*ListTasksByPurchaseIdResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{24}
}

func (x *ListTasksByPurchaseIdResponse) GetTasks() []*Task {
	if x != nil {
		return x.Tasks
	}
	return nil
}

type MarkTaskAsDoneRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkTaskAsDoneRequest) Reset() {
	*x = MarkTaskAsDoneRequest{}
	mi := &file_purchase_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkTaskAsDoneRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTaskAsDoneRequest) ProtoMessage() {}

func (x *MarkTaskAsDoneRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTaskAsDoneRequest.ProtoReflect.Descriptor instead.
func (*MarkTaskAsDoneRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{25}
}

func (x *MarkTaskAsDoneRequest) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

type MarkTaskAsDoneResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkTaskAsDoneResponse) Reset() {
	*x = MarkTaskAsDoneResponse{}
	mi := &file_purchase_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkTaskAsDoneResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkTaskAsDoneResponse) ProtoMessage() {}

func (x *MarkTaskAsDoneResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkTaskAsDoneResponse.ProtoReflect.Descriptor instead.
func (*MarkTaskAsDoneResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{26}
}

func (x *MarkTaskAsDoneResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type LockPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockPurchaseRequest) Reset() {
	*x = LockPurchaseRequest{}
	mi := &file_purchase_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockPurchaseRequest) ProtoMessage() {}

func (x *LockPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockPurchaseRequest.ProtoReflect.Descriptor instead.
func (*LockPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{27}
}

func (x *LockPurchaseRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type LockPurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockPurchaseResponse) Reset() {
	*x = LockPurchaseResponse{}
	mi := &file_purchase_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockPurchaseResponse) ProtoMessage() {}

func (x *LockPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockPurchaseResponse.ProtoReflect.Descriptor instead.
func (*LockPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{28}
}

func (x *LockPurchaseResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type UnlockPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockPurchaseRequest) Reset() {
	*x = UnlockPurchaseRequest{}
	mi := &file_purchase_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockPurchaseRequest) ProtoMessage() {}

func (x *UnlockPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockPurchaseRequest.ProtoReflect.Descriptor instead.
func (*UnlockPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{29}
}

func (x *UnlockPurchaseRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type UnlockPurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlockPurchaseResponse) Reset() {
	*x = UnlockPurchaseResponse{}
	mi := &file_purchase_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlockPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlockPurchaseResponse) ProtoMessage() {}

func (x *UnlockPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlockPurchaseResponse.ProtoReflect.Descriptor instead.
func (*UnlockPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{30}
}

func (x *UnlockPurchaseResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type CanUnlockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanUnlockRequest) Reset() {
	*x = CanUnlockRequest{}
	mi := &file_purchase_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanUnlockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanUnlockRequest) ProtoMessage() {}

func (x *CanUnlockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanUnlockRequest.ProtoReflect.Descriptor instead.
func (*CanUnlockRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{31}
}

func (x *CanUnlockRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type CanUnlockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CanUpdate     bool                   `protobuf:"varint,1,opt,name=can_update,json=canUpdate,proto3" json:"can_update,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CanUnlockResponse) Reset() {
	*x = CanUnlockResponse{}
	mi := &file_purchase_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CanUnlockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanUnlockResponse) ProtoMessage() {}

func (x *CanUnlockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanUnlockResponse.ProtoReflect.Descriptor instead.
func (*CanUnlockResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{32}
}

func (x *CanUnlockResponse) GetCanUpdate() bool {
	if x != nil {
		return x.CanUpdate
	}
	return false
}

type GetSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotRequest) Reset() {
	*x = GetSnapshotRequest{}
	mi := &file_purchase_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotRequest) ProtoMessage() {}

func (x *GetSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotRequest.ProtoReflect.Descriptor instead.
func (*GetSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{33}
}

func (x *GetSnapshotRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type GetSnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      *Snapshot              `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSnapshotResponse) Reset() {
	*x = GetSnapshotResponse{}
	mi := &file_purchase_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSnapshotResponse) ProtoMessage() {}

func (x *GetSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSnapshotResponse.ProtoReflect.Descriptor instead.
func (*GetSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{34}
}

func (x *GetSnapshotResponse) GetSnapshot() *Snapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

type MarkSettlementInitiatedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkSettlementInitiatedRequest) Reset() {
	*x = MarkSettlementInitiatedRequest{}
	mi := &file_purchase_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkSettlementInitiatedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkSettlementInitiatedRequest) ProtoMessage() {}

func (x *MarkSettlementInitiatedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkSettlementInitiatedRequest.ProtoReflect.Descriptor instead.
func (*MarkSettlementInitiatedRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{35}
}

func (x *MarkSettlementInitiatedRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type MarkSettlementInitiatedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkSettlementInitiatedResponse) Reset() {
	*x = MarkSettlementInitiatedResponse{}
	mi := &file_purchase_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkSettlementInitiatedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkSettlementInitiatedResponse) ProtoMessage() {}

func (x *MarkSettlementInitiatedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkSettlementInitiatedResponse.ProtoReflect.Descriptor instead.
func (*MarkSettlementInitiatedResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{36}
}

func (x *MarkSettlementInitiatedResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type FinishPurchaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PurchaseId    string                 `protobuf:"bytes,1,opt,name=purchase_id,json=purchaseId,proto3" json:"purchase_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishPurchaseRequest) Reset() {
	*x = FinishPurchaseRequest{}
	mi := &file_purchase_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishPurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishPurchaseRequest) ProtoMessage() {}

func (x *FinishPurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishPurchaseRequest.ProtoReflect.Descriptor instead.
func (*FinishPurchaseRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{37}
}

func (x *FinishPurchaseRequest) GetPurchaseId() string {
	if x != nil {
		return x.PurchaseId
	}
	return ""
}

type FinishPurchaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinishPurchaseResponse) Reset() {
	*x = FinishPurchaseResponse{}
	mi := &file_purchase_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishPurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishPurchaseResponse) ProtoMessage() {}

func (x *FinishPurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishPurchaseResponse.ProtoReflect.Descriptor instead.
func (*FinishPurchaseResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{38}
}

func (x *FinishPurchaseResponse) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type HealthRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Empty         *emptypb.Empty         `protobuf:"bytes,1,opt,name=empty,proto3" json:"empty,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthRequest) Reset() {
	*x = HealthRequest{}
	mi := &file_purchase_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthRequest) ProtoMessage() {}

func (x *HealthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthRequest.ProtoReflect.Descriptor instead.
func (*HealthRequest) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{39}
}

func (x *HealthRequest) GetEmpty() *emptypb.Empty {
	if x != nil {
		return x.Empty
	}
	return nil
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_purchase_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_purchase_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_purchase_proto_rawDescGZIP(), []int{40}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_purchase_proto protoreflect.FileDescriptor

const file_purchase_proto_rawDesc = "" +
	"\n" +
	"\x0epurchase.proto\x12\bpurchase\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd0\x02\n" +
	"\bPurchase\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12R\n" +
	"\x17settlement_initiated_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\x15settlementInitiatedAt\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x127\n" +
	"\tlocked_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\blockedAt\x12;\n" +
	"\vfinished_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"finishedAt\"\xeb\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vpurchase_id\x18\x04 \x01(\tR\n" +
	"purchaseId\x12$\n" +
	"\x0eauthor_user_id\x18\x05 \x01(\tR\fauthorUserId\x12(\n" +
	"\x10executor_user_id\x18\x06 \x01(\tR\x0eexecutorUserId\x12\x12\n" +
	"\x04done\x18\a \x01(\bR\x04done\x12\x16\n" +
	"\x06amount\x18\b \x01(\x03R\x06amount\"\xc6\x01\n" +
	"\bSnapshot\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\x12%\n" +
	"\x0epurchase_title\x18\x02 \x01(\tR\rpurchaseTitle\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\x12$\n" +
	"\x05tasks\x18\x04 \x03(\v2\x0e.purchase.TaskR\x05tasks\x120\n" +
	"\x14participant_user_ids\x18\x05 \x03(\tR\x12participantUserIds\"k\n" +
	"\x15CreatePurchaseRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1a\n" +
	"\bcurrency\x18\x03 \x01(\tR\bcurrency\"9\n" +
	"\x16CreatePurchaseResponse\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"5\n" +
	"\x12GetPurchaseRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"E\n" +
	"\x13GetPurchaseResponse\x12.\n" +
	"\bpurchase\x18\x01 \x01(\v2\x12.purchase.PurchaseR\bpurchase\"D\n" +
	"\x14ListPurchasesRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"I\n" +
	"\x15ListPurchasesResponse\x120\n" +
	"\tpurchases\x18\x01 \x03(\v2\x12.purchase.PurchaseR\tpurchases\"6\n" +
	"\x13CreateInviteRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x03 \x01(\tR\n" +
	"purchaseId\"d\n" +
	"\x14CreateInviteResponse\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\"D\n" +
	"\x13JoinByInviteRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\"D\n" +
	"\x14JoinByInviteResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"T\n" +
	"\x18RemoveParticipantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1f\n" +
	"\vpurchase_id\x18\x02 \x01(\tR\n" +
	"purchaseId\"I\n" +
	"\x19RemoveParticipantResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"F\n" +
	"#ListParticipantsByPurchaseIdRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"A\n" +
	"$ListParticipantsByPurchaseIdResponse\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\"\xaa\x01\n" +
	"\x11CreateTaskRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x1f\n" +
	"\vpurchase_id\x18\x03 \x01(\tR\n" +
	"purchaseId\x12$\n" +
	"\x0eauthor_user_id\x18\x04 \x01(\tR\fauthorUserId\x12\x16\n" +
	"\x06amount\x18\x05 \x01(\x03R\x06amount\"-\n" +
	"\x12CreateTaskResponse\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"T\n" +
	"\x0fTakeTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12(\n" +
	"\x10executor_user_id\x18\x02 \x01(\tR\x0eexecutorUserId\"@\n" +
	"\x10TakeTaskResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\",\n" +
	"\x11DeleteTaskRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"B\n" +
	"\x12DeleteTaskResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"?\n" +
	"\x1cListTasksByPurchaseIdRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"E\n" +
	"\x1dListTasksByPurchaseIdResponse\x12$\n" +
	"\x05tasks\x18\x01 \x03(\v2\x0e.purchase.TaskR\x05tasks\"0\n" +
	"\x15MarkTaskAsDoneRequest\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\"F\n" +
	"\x16MarkTaskAsDoneResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"6\n" +
	"\x13LockPurchaseRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"D\n" +
	"\x14LockPurchaseResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"8\n" +
	"\x15UnlockPurchaseRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"F\n" +
	"\x16UnlockPurchaseResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"3\n" +
	"\x10CanUnlockRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"2\n" +
	"\x11CanUnlockResponse\x12\x1d\n" +
	"\n" +
	"can_update\x18\x01 \x01(\bR\tcanUpdate\"5\n" +
	"\x12GetSnapshotRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"E\n" +
	"\x13GetSnapshotResponse\x12.\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x12.purchase.SnapshotR\bsnapshot\"A\n" +
	"\x1eMarkSettlementInitiatedRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"O\n" +
	"\x1fMarkSettlementInitiatedResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"8\n" +
	"\x15FinishPurchaseRequest\x12\x1f\n" +
	"\vpurchase_id\x18\x01 \x01(\tR\n" +
	"purchaseId\"F\n" +
	"\x16FinishPurchaseResponse\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"=\n" +
	"\rHealthRequest\x12,\n" +
	"\x05empty\x18\x01 \x01(\v2\x16.google.protobuf.EmptyR\x05empty\"(\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status2\xf1\f\n" +
	"\x0fPurchaseService\x12U\n" +
	"\x0eCreatePurchase\x12\x1f.purchase.CreatePurchaseRequest\x1a .purchase.CreatePurchaseResponse\"\x00\x12L\n" +
	"\vGetPurchase\x12\x1c.purchase.GetPurchaseRequest\x1a\x1d.purchase.GetPurchaseResponse\"\x00\x12R\n" +
	"\rListPurchases\x12\x1e.purchase.ListPurchasesRequest\x1a\x1f.purchase.ListPurchasesResponse\"\x00\x12O\n" +
	"\fCreateInvite\x12\x1d.purchase.CreateInviteRequest\x1a\x1e.purchase.CreateInviteResponse\"\x00\x12O\n" +
	"\fJoinByInvite\x12\x1d.purchase.JoinByInviteRequest\x1a\x1e.purchase.JoinByInviteResponse\"\x00\x12^\n" +
	"\x11RemoveParticipant\x12\".purchase.RemoveParticipantRequest\x1a#.purchase.RemoveParticipantResponse\"\x00\x12\x7f\n" +
	"\x1cListParticipantsByPurchaseId\x12-.purchase.ListParticipantsByPurchaseIdRequest\x1a..purchase.ListParticipantsByPurchaseIdResponse\"\x00\x12I\n" +
	"\n" +
	"CreateTask\x12\x1b.purchase.CreateTaskRequest\x1a\x1c.purchase.CreateTaskResponse\"\x00\x12C\n" +
	"\bTakeTask\x12\x19.purchase.TakeTaskRequest\x1a\x1a.purchase.TakeTaskResponse\"\x00\x12I\n" +
	"\n" +
	"DeleteTask\x12\x1b.purchase.DeleteTaskRequest\x1a\x1c.purchase.DeleteTaskResponse\"\x00\x12j\n" +
	"\x15ListTasksByPurchaseId\x12&.purchase.ListTasksByPurchaseIdRequest\x1a'.purchase.ListTasksByPurchaseIdResponse\"\x00\x12U\n" +
	"\x0eMarkTaskAsDone\x12\x1f.purchase.MarkTaskAsDoneRequest\x1a .purchase.MarkTaskAsDoneResponse\"\x00\x12O\n" +
	"\fLockPurchase\x12\x1d.purchase.LockPurchaseRequest\x1a\x1e.purchase.LockPurchaseResponse\"\x00\x12U\n" +
	"\x0eUnlockPurchase\x12\x1f.purchase.UnlockPurchaseRequest\x1a .purchase.UnlockPurchaseResponse\"\x00\x12F\n" +
	"\tCanUnlock\x12\x1a.purchase.CanUnlockRequest\x1a\x1b.purchase.CanUnlockResponse\"\x00\x12L\n" +
	"\vGetSnapshot\x12\x1c.purchase.GetSnapshotRequest\x1a\x1d.purchase.GetSnapshotResponse\"\x00\x12p\n" +
	"\x17MarkSettlementInitiated\x12(.purchase.MarkSettlementInitiatedRequest\x1a).purchase.MarkSettlementInitiatedResponse\"\x00\x12U\n" +
	"\x0eFinishPurchase\x12\x1f.purchase.FinishPurchaseRequest\x1a .purchase.FinishPurchaseResponse\"\x00\x12=\n" +
	"\x06Health\x12\x17.purchase.HealthRequest\x1a\x18.purchase.HealthResponse\"\x00BUZSgithub.com/nikitadev-work/SyncBuyProject/services/purchase/proto-codegen;purchasepbb\x06proto3"

var (
	file_purchase_proto_rawDescOnce sync.Once
	file_purchase_proto_rawDescData []byte
)

func file_purchase_proto_rawDescGZIP() []byte {
	file_purchase_proto_rawDescOnce.Do(func() {
		file_purchase_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_purchase_proto_rawDesc), len(file_purchase_proto_rawDesc)))
	})
	return file_purchase_proto_rawDescData
}

var file_purchase_proto_msgTypes = make([]protoimpl.MessageInfo, 41)
var file_purchase_proto_goTypes = []any{
	(*Purchase)(nil),                             // 0: purchase.Purchase
	(*Task)(nil),                                 // 1: purchase.Task
	(*Snapshot)(nil),                             // 2: purchase.Snapshot
	(*CreatePurchaseRequest)(nil),                // 3: purchase.CreatePurchaseRequest
	(*CreatePurchaseResponse)(nil),               // 4: purchase.CreatePurchaseResponse
	(*GetPurchaseRequest)(nil),                   // 5: purchase.GetPurchaseRequest
	(*GetPurchaseResponse)(nil),                  // 6: purchase.GetPurchaseResponse
	(*ListPurchasesRequest)(nil),                 // 7: purchase.ListPurchasesRequest
	(*ListPurchasesResponse)(nil),                // 8: purchase.ListPurchasesResponse
	(*CreateInviteRequest)(nil),                  // 9: purchase.CreateInviteRequest
	(*CreateInviteResponse)(nil),                 // 10: purchase.CreateInviteResponse
	(*JoinByInviteRequest)(nil),                  // 11: purchase.JoinByInviteRequest
	(*JoinByInviteResponse)(nil),                 // 12: purchase.JoinByInviteResponse
	(*RemoveParticipantRequest)(nil),             // 13: purchase.RemoveParticipantRequest
	(*RemoveParticipantResponse)(nil),            // 14: purchase.RemoveParticipantResponse
	(*ListParticipantsByPurchaseIdRequest)(nil),  // 15: purchase.ListParticipantsByPurchaseIdRequest
	(*ListParticipantsByPurchaseIdResponse)(nil), // 16: purchase.ListParticipantsByPurchaseIdResponse
	(*CreateTaskRequest)(nil),                    // 17: purchase.CreateTaskRequest
	(*CreateTaskResponse)(nil),                   // 18: purchase.CreateTaskResponse
	(*TakeTaskRequest)(nil),                      // 19: purchase.TakeTaskRequest
	(*TakeTaskResponse)(nil),                     // 20: purchase.TakeTaskResponse
	(*DeleteTaskRequest)(nil),                    // 21: purchase.DeleteTaskRequest
	(*DeleteTaskResponse)(nil),                   // 22: purchase.DeleteTaskResponse
	(*ListTasksByPurchaseIdRequest)(nil),         // 23: purchase.ListTasksByPurchaseIdRequest
	(*ListTasksByPurchaseIdResponse)(nil),        // 24: purchase.ListTasksByPurchaseIdResponse
	(*MarkTaskAsDoneRequest)(nil),                // 25: purchase.MarkTaskAsDoneRequest
	(*MarkTaskAsDoneResponse)(nil),               // 26: purchase.MarkTaskAsDoneResponse
	(*LockPurchaseRequest)(nil),                  // 27: purchase.LockPurchaseRequest
	(*LockPurchaseResponse)(nil),                 // 28: purchase.LockPurchaseResponse
	(*UnlockPurchaseRequest)(nil),                // 29: purchase.UnlockPurchaseRequest
	(*UnlockPurchaseResponse)(nil),               // 30: purchase.UnlockPurchaseResponse
	(*CanUnlockRequest)(nil),                     // 31: purchase.CanUnlockRequest
	(*CanUnlockResponse)(nil),                    // 32: purchase.CanUnlockResponse
	(*GetSnapshotRequest)(nil),                   // 33: purchase.GetSnapshotRequest
	(*GetSnapshotResponse)(nil),                  // 34: purchase.GetSnapshotResponse
	(*MarkSettlementInitiatedRequest)(nil),       // 35: purchase.MarkSettlementInitiatedRequest
	(*MarkSettlementInitiatedResponse)(nil),      // 36: purchase.MarkSettlementInitiatedResponse
	(*FinishPurchaseRequest)(nil),                // 37: purchase.FinishPurchaseRequest
	(*FinishPurchaseResponse)(nil),               // 38: purchase.FinishPurchaseResponse
	(*HealthRequest)(nil),                        // 39: purchase.HealthRequest
	(*HealthResponse)(nil),                       // 40: purchase.HealthResponse
	(*timestamppb.Timestamp)(nil),                // 41: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                        // 42: google.protobuf.Empty
}
var file_purchase_proto_depIdxs = []int32{
	41, // 0: purchase.Purchase.settlement_initiated_at:type_name -> google.protobuf.Timestamp
	41, // 1: purchase.Purchase.locked_at:type_name -> google.protobuf.Timestamp
	41, // 2: purchase.Purchase.finished_at:type_name -> google.protobuf.Timestamp
	1,  // 3: purchase.Snapshot.tasks:type_name -> purchase.Task
	0,  // 4: purchase.GetPurchaseResponse.purchase:type_name -> purchase.Purchase
	42, // 5: purchase.ListPurchasesRequest.empty:type_name -> google.protobuf.Empty
	0,  // 6: purchase.ListPurchasesResponse.purchases:type_name -> purchase.Purchase
	42, // 7: purchase.JoinByInviteResponse.empty:type_name -> google.protobuf.Empty
	42, // 8: purchase.RemoveParticipantResponse.empty:type_name -> google.protobuf.Empty
	42, // 9: purchase.TakeTaskResponse.empty:type_name -> google.protobuf.Empty
	42, // 10: purchase.DeleteTaskResponse.empty:type_name -> google.protobuf.Empty
	1,  // 11: purchase.ListTasksByPurchaseIdResponse.tasks:type_name -> purchase.Task
	42, // 12: purchase.MarkTaskAsDoneResponse.empty:type_name -> google.protobuf.Empty
	42, // 13: purchase.LockPurchaseResponse.empty:type_name -> google.protobuf.Empty
	42, // 14: purchase.UnlockPurchaseResponse.empty:type_name -> google.protobuf.Empty
	2,  // 15: purchase.GetSnapshotResponse.snapshot:type_name -> purchase.Snapshot
	42, // 16: purchase.MarkSettlementInitiatedResponse.empty:type_name -> google.protobuf.Empty
	42, // 17: purchase.FinishPurchaseResponse.empty:type_name -> google.protobuf.Empty
	42, // 18: purchase.HealthRequest.empty:type_name -> google.protobuf.Empty
	3,  // 19: purchase.PurchaseService.CreatePurchase:input_type -> purchase.CreatePurchaseRequest
	5,  // 20: purchase.PurchaseService.GetPurchase:input_type -> purchase.GetPurchaseRequest
	7,  // 21: purchase.PurchaseService.ListPurchases:input_type -> purchase.ListPurchasesRequest
	9,  // 22: purchase.PurchaseService.CreateInvite:input_type -> purchase.CreateInviteRequest
	11, // 23: purchase.PurchaseService.JoinByInvite:input_type -> purchase.JoinByInviteRequest
	13, // 24: purchase.PurchaseService.RemoveParticipant:input_type -> purchase.RemoveParticipantRequest
	15, // 25: purchase.PurchaseService.ListParticipantsByPurchaseId:input_type -> purchase.ListParticipantsByPurchaseIdRequest
	17, // 26: purchase.PurchaseService.CreateTask:input_type -> purchase.CreateTaskRequest
	19, // 27: purchase.PurchaseService.TakeTask:input_type -> purchase.TakeTaskRequest
	21, // 28: purchase.PurchaseService.DeleteTask:input_type -> purchase.DeleteTaskRequest
	23, // 29: purchase.PurchaseService.ListTasksByPurchaseId:input_type -> purchase.ListTasksByPurchaseIdRequest
	25, // 30: purchase.PurchaseService.MarkTaskAsDone:input_type -> purchase.MarkTaskAsDoneRequest
	27, // 31: purchase.PurchaseService.LockPurchase:input_type -> purchase.LockPurchaseRequest
	29, // 32: purchase.PurchaseService.UnlockPurchase:input_type -> purchase.UnlockPurchaseRequest
	31, // 33: purchase.PurchaseService.CanUnlock:input_type -> purchase.CanUnlockRequest
	33, // 34: purchase.PurchaseService.GetSnapshot:input_type -> purchase.GetSnapshotRequest
	35, // 35: purchase.PurchaseService.MarkSettlementInitiated:input_type -> purchase.MarkSettlementInitiatedRequest
	37, // 36: purchase.PurchaseService.FinishPurchase:input_type -> purchase.FinishPurchaseRequest
	39, // 37: purchase.PurchaseService.Health:input_type -> purchase.HealthRequest
	4,  // 38: purchase.PurchaseService.CreatePurchase:output_type -> purchase.CreatePurchaseResponse
	6,  // 39: purchase.PurchaseService.GetPurchase:output_type -> purchase.GetPurchaseResponse
	8,  // 40: purchase.PurchaseService.ListPurchases:output_type -> purchase.ListPurchasesResponse
	10, // 41: purchase.PurchaseService.CreateInvite:output_type -> purchase.CreateInviteResponse
	12, // 42: purchase.PurchaseService.JoinByInvite:output_type -> purchase.JoinByInviteResponse
	14, // 43: purchase.PurchaseService.RemoveParticipant:output_type -> purchase.RemoveParticipantResponse
	16, // 44: purchase.PurchaseService.ListParticipantsByPurchaseId:output_type -> purchase.ListParticipantsByPurchaseIdResponse
	18, // 45: purchase.PurchaseService.CreateTask:output_type -> purchase.CreateTaskResponse
	20, // 46: purchase.PurchaseService.TakeTask:output_type -> purchase.TakeTaskResponse
	22, // 47: purchase.PurchaseService.DeleteTask:output_type -> purchase.DeleteTaskResponse
	24, // 48: purchase.PurchaseService.ListTasksByPurchaseId:output_type -> purchase.ListTasksByPurchaseIdResponse
	26, // 49: purchase.PurchaseService.MarkTaskAsDone:output_type -> purchase.MarkTaskAsDoneResponse
	28, // 50: purchase.PurchaseService.LockPurchase:output_type -> purchase.LockPurchaseResponse
	30, // 51: purchase.PurchaseService.UnlockPurchase:output_type -> purchase.UnlockPurchaseResponse
	32, // 52: purchase.PurchaseService.CanUnlock:output_type -> purchase.CanUnlockResponse
	34, // 53: purchase.PurchaseService.GetSnapshot:output_type -> purchase.GetSnapshotResponse
	36, // 54: purchase.PurchaseService.MarkSettlementInitiated:output_type -> purchase.MarkSettlementInitiatedResponse
	38, // 55: purchase.PurchaseService.FinishPurchase:output_type -> purchase.FinishPurchaseResponse
	40, // 56: purchase.PurchaseService.Health:output_type -> purchase.HealthResponse
	38, // [38:57] is the sub-list for method output_type
	19, // [19:38] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_purchase_proto_init() }
func file_purchase_proto_init() {
	if File_purchase_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_purchase_proto_rawDesc), len(file_purchase_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   41,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_purchase_proto_goTypes,
		DependencyIndexes: file_purchase_proto_depIdxs,
		MessageInfos:      file_purchase_proto_msgTypes,
	}.Build()
	File_purchase_proto = out.File
	file_purchase_proto_goTypes = nil
	file_purchase_proto_depIdxs = nil
}
